### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fabiovieitas** [RoNzzzz/BIngSearcher#1]
Good afternoon.

Is it possible for him to do the answers automatically, just like the ABS?

**Comment by RohanPhuyal** [comment]
> 

I am just begineer to the Javascript, but I'll try to implement it, probably this week :)

**Comment by fabiovieitas** [comment]
thanks for the attention!

**Comment by RohanPhuyal** [comment]
> 
I added the auto click but it might not still be best, but you can try new commit. Will be uploading release after some hours. Thanks

**Comment by RohanPhuyal** [comment]
> thanks for the attention!

I forgot to mention It is currently implemented on Fix Button, I'll do cleanups and put only one button later when I'm home might take less than 8 hours

**Comment by fabiovieitas** [comment]
Thanks! As soon as it comes out I'll test it!!!!!!
