### ISSUE TITLE
Bing searcher not working with my account, but with others works fine

### ISSUE THREAD

**Issue by JafethTheXtreme** [RoNzzzz/BIngSearcher#10]
Hey, I got a problem when use it with my account, maybe its a problem of my own but I dont undestand why with my other accounts worked perfectly but with mine dont, I got this message from the console tab
![error](https://github.com/RoNzzzz/BIngSearcher/assets/144962155/55ec7fc2-8c4b-497e-9d97-b77558aec6bf)

**Comment by RohanPhuyal** [comment]
there's no longer shopping game :(
