### ISSUE TITLE
Microsoft patched the MSN Shopping Game script

### ISSUE THREAD

**Issue by Chappie18** [RoNzzzz/BIngSearcher#2]
Today, June 20, 2023, Microsoft patched the MSN Shopping Game script.
Can you update the extension files to use the latest fixes for msn shopping?

**Comment by RohanPhuyal** [comment]
> Today, June 20, 2023, Microsoft patched the MSN Shopping Game script. Can you update the extension files to use the latest fixes for msn shopping?

Updated it in v7.0, check it out. Not yet fully optimized but works fine :)
Will be optimizing when I have more time. But it works

**Comment by Chappie18** [comment]
I appreciate your quick reaction and fix.
