### ISSUE TITLE
Auto game not working

### ISSUE THREAD

**Issue by bhargav981** [RoNzzzz/BIngSearcher#5]
The auto game for shopping is not working. I tried in 10 separate accounts didn't work in any of them only manual search is working

**Comment by RohanPhuyal** [comment]
> The auto game for shopping is not working. I tried in 10 separate accounts didn't work in any of them only manual search is working

It works when you select at least one option manually.

**Comment by bhargav981** [comment]
so I have to select an option before starting the game? If so I could select the wrong answer then, Anyway, it doesn't matter now since the game isn't working for anyone even without the script. Thanks for your work

**Comment by RohanPhuyal** [comment]
> so I have to select an option before starting the game? If so I could select the wrong answer then, Anyway, it doesn't matter now since the game isn't working for anyone even without the script. Thanks for your work

Try the new updated extension, it got better msn shopping script (for those whose point is increasing)
