### ISSUE TITLE
Please Update MSN Shopping script.

### ISSUE THREAD

**Issue by arijit64** [RoNzzzz/BIngSearcher#6]
The new updated 'MSN Shopping Script' is no longer giving points. Please update it.

**Comment by RohanPhuyal** [comment]
I'm trying to find out the problem and solution to it, will update soon

**Comment by RohanPhuyal** [comment]
> The new updated 'MSN Shopping Script' is no longer giving points. Please update it.

Try the new v8.0, The whole script and extension has been changed :)
