### ISSUE TITLE
Updated script for the MSN Shopping Script alone

### ISSUE THREAD

**Issue by Chappie18** [RoNzzzz/BIngSearcher#8]
Hey, it appears that the MSN Shopping Game patch wave is complete; could you maybe provide me with the updated auto msn shopping extension with an 11-second gap!

**Comment by RohanPhuyal** [comment]
> 

It's working rn, I'll extend it to 11-second coming patch :)

**Comment by Chappie18** [comment]
Thank you so much; I really appreciate it.

**Comment by Chappie18** [comment]
> > 
> 
> It's working rn, I'll extend it to 11-second coming patch :)

Any updates

**Comment by RohanPhuyal** [comment]
> 

the whole script needs to be remade :)

**Comment by RohanPhuyal** [comment]
> > > 
> > 
> > 
> > It's working rn, I'll extend it to 11-second coming patch :)
> 
> Any updates

I haven't increased the timer but the script is updated and working after today 2023-08-29

**Comment by Chappie18** [comment]
> > > > 
> > > 
> > > 
> > > It's working rn, I'll extend it to 11-second coming patch :)
> > 
> > 
> > Any updates
> 
> I haven't increased the timer but the script is updated and working after today 2023-08-29

could you maybe provide me with the updated **Auto MSN Shopping Extension** with an 11-second gap!
