### ISSUE TITLE
The Mobile Search no longer counts

### ISSUE THREAD

**Issue by ibigfire** [RoNzzzz/BIngSearcher#9]
Thank you for this.

Unfortunately the mobile section of the searches no longer works.  It does the searches, but doesn't count toward the mobile searches on the rewards page.

**Comment by RohanPhuyal** [comment]
> 

it should work now, or remove the profile in browser and make new profile and login there

**Comment by ibigfire** [comment]
Yep, it does work now.  Thanks for the fix!
